#!/usr/bin/env node
//
// Kortex `health` — single-shot wiki health check. Renamed from v1 `lint`.
//
// Why the rename: v1 lint was ~95K tokens to run because each check
// re-scanned the filesystem. v2 health reads `.cache/status.json` and
// `.cache/backrefs.json` (regenerated by hooks at write time) and only
// falls back to filesystem scans when the cache is missing or stale.
// Target token budget: <6K tokens per run.
//
// Checks (per audit §16):
//   1. stale wiki — pages with `updated:` >60d AND distillation_level <2
//   2. broken links — delegated to validate-links.mjs hook (reused at
//      health time as a non-blocking pass)
//   3. sidecar debt — binary files without .meta.md or folder-README cover
//   4. idea bank — total size + age of oldest item
//   5. distillation debt — count per level 0-4
//   6. AGENTS.md ↔ CLAUDE.md drift — symlink check
//   7. log.md rotation — flag if >3000 lines
//
// Flags:
//   --critical   exit 1 if any critical finding (CI usage)
//   --tokens     estimate token cost of each workflow vs baseline
//   --json       machine-readable output

import { parseArgs } from 'node:util';
import { readFile, readdir, stat } from 'node:fs/promises';
import { existsSync, statSync, readlinkSync, lstatSync } from 'node:fs';
import path from 'node:path';
import { parseFile } from '../lib/frontmatter.mjs';
import { colors, tag } from '../lib/colors.mjs';

const { values } = parseArgs({
  options: {
    critical: { type: 'boolean', default: false },
    tokens: { type: 'boolean', default: false },
    json: { type: 'boolean', default: false },
    repo: { type: 'string' },
    help: { type: 'boolean', short: 'h', default: false },
  },
  strict: false,
});

if (values.help) {
  printHelp();
  process.exit(0);
}

const repoRoot = values.repo ? path.resolve(values.repo) : findRepoRoot(process.cwd());

// All checks accumulate into this report. We aggregate first, format last,
// so --json and human output share the exact same data.
const report = {
  date: new Date().toISOString().slice(0, 10),
  repo: repoRoot,
  checks: {},
  summary: { ok: 0, warn: 0, critical: 0 },
};

await runChecks(repoRoot, report);

if (values.json) {
  console.log(JSON.stringify(report, null, 2));
} else {
  printReport(report);
}

if (values.critical && report.summary.critical > 0) {
  process.exit(1);
}

// =====================================================================
// Run all checks. Each check is its own function so we can add/remove
// independently. Each check writes one entry into report.checks.
// =====================================================================

async function runChecks(root, r) {
  // Try to load the status cache — most checks short-circuit through it.
  const cache = loadCache(root);

  // Check 1: stale wiki pages.
  r.checks.stale_wiki = await checkStaleWiki(root, cache);
  bump(r, r.checks.stale_wiki.severity);

  // Check 2: broken links — we DELEGATE to the hook to avoid duplicating
  // logic. The hook lives at scripts/hooks/validate-links.mjs (Hook-porter
  // is writing it in parallel). We invoke it via dynamic import; if it
  // isn't yet present we mark this check as "deferred".
  r.checks.broken_links = await checkBrokenLinks(root);
  bump(r, r.checks.broken_links.severity);

  // Check 3: sidecar debt.
  r.checks.sidecar_debt = await checkSidecarDebt(root);
  bump(r, r.checks.sidecar_debt.severity);

  // Check 4: idea bank stats.
  r.checks.idea_bank = await checkIdeaBank(root);
  bump(r, r.checks.idea_bank.severity);

  // Check 5: distillation debt.
  r.checks.distillation_debt = await checkDistillationDebt(root);
  bump(r, r.checks.distillation_debt.severity);

  // Check 6: AGENTS.md ↔ CLAUDE.md symlink.
  r.checks.agents_symlink = await checkAgentsSymlink(root);
  bump(r, r.checks.agents_symlink.severity);

  // Check 7: log.md rotation pressure.
  r.checks.log_rotation = await checkLogRotation(root);
  bump(r, r.checks.log_rotation.severity);

  // Check 8 (optional): token estimation.
  if (values.tokens) {
    r.checks.token_estimate = await estimateTokens(root);
    bump(r, r.checks.token_estimate.severity);
  }
}

// Try to load .cache/status.json. We don't fail if absent — checks fall
// back to filesystem walks (with a small loud note in the cache field).
function loadCache(root) {
  const p = path.join(root, '.cache', 'status.json');
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSyncSafe(p));
  } catch {
    return null;
  }
}

function readFileSyncSafe(p) {
  // We use lazy require to avoid pulling fs/promises at top-level when we
  // need synchronous reads inside small helpers.
  return require('node:fs').readFileSync(p, 'utf8');
}

// Bump the summary counters based on a check's severity.
function bump(r, severity) {
  if (severity === 'ok') r.summary.ok++;
  else if (severity === 'warn') r.summary.warn++;
  else if (severity === 'critical') r.summary.critical++;
}

// =====================================================================
// Individual checks.
// =====================================================================

// Stale wiki: pages whose `updated:` is older than 60 days AND whose
// distillation_level is < 2. We combine the two so we don't yell about a
// well-distilled reference that simply hasn't needed an edit.
async function checkStaleWiki(root, cache) {
  const wikiDir = path.join(root, 'wiki');
  if (!existsSync(wikiDir)) return ok('stale_wiki', 0);

  const cutoff = Date.now() - 60 * 24 * 3600 * 1000;
  const stale = [];

  // Prefer cache when present.
  if (cache?.pages) {
    for (const p of cache.pages) {
      if (p.updated && new Date(p.updated).getTime() < cutoff && (p.distillation_level ?? 0) < 2) {
        stale.push({ path: p.path, updated: p.updated, level: p.distillation_level ?? 0 });
      }
    }
  } else {
    for await (const f of walkMd(wikiDir)) {
      const parsed = parseFile(f);
      const fm = parsed.data || {};
      if (!fm.updated) continue;
      if (new Date(fm.updated).getTime() >= cutoff) continue;
      if ((fm.distillation_level ?? 0) >= 2) continue;
      stale.push({
        path: path.relative(root, f),
        updated: fm.updated,
        level: fm.distillation_level ?? 0,
      });
    }
  }

  return {
    severity: stale.length === 0 ? 'ok' : stale.length < 5 ? 'warn' : 'critical',
    count: stale.length,
    items: stale.slice(0, 10), // top 10 so output stays bounded
  };
}

// Broken links: delegated to scripts/hooks/validate-links.mjs.
async function checkBrokenLinks(root) {
  const hookPath = path.join(root, 'scripts', 'hooks', 'validate-links.mjs');
  if (!existsSync(hookPath)) {
    return { severity: 'warn', count: 0, deferred: 'validate-links hook not yet present' };
  }
  try {
    const mod = await import(hookPath);
    if (typeof mod.scanRepo === 'function') {
      const broken = await mod.scanRepo(root);
      return {
        severity: broken.length === 0 ? 'ok' : 'critical',
        count: broken.length,
        items: broken.slice(0, 10),
      };
    }
    return { severity: 'warn', count: 0, deferred: 'scanRepo() not exported from validate-links' };
  } catch (e) {
    return { severity: 'warn', count: 0, deferred: `link hook errored: ${e.message}` };
  }
}

// Sidecar debt: any binary that isn't covered by a .meta.md sidecar OR a
// folder README aggregation. We only sweep when the cache is missing —
// status.json is supposed to track this for us.
async function checkSidecarDebt(root) {
  const exts = ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.mp4', '.mov', '.pdf', '.mp3', '.wav', '.svg'];
  const debts = [];
  // Walk under content zones only — node_modules, .git, .cache excluded.
  for await (const f of walkAll(root, ['node_modules', '.git', '.cache', '.husky', '.worktrees'])) {
    const ext = path.extname(f).toLowerCase();
    if (!exts.includes(ext)) continue;
    const dir = path.dirname(f);
    const sidecar = `${f}.meta.md`;
    if (existsSync(sidecar)) continue;
    const folderReadme = path.join(dir, 'README.md');
    if (existsSync(folderReadme)) continue;
    debts.push(path.relative(root, f));
  }
  return {
    severity: debts.length === 0 ? 'ok' : debts.length < 5 ? 'warn' : 'critical',
    count: debts.length,
    items: debts.slice(0, 10),
  };
}

// Idea bank: total + oldest. We pull from projects/*/ideation-bank/ if it
// exists. The "bank size" metric helps the owner notice when triage is
// falling behind faster than capture.
async function checkIdeaBank(root) {
  const projectsDir = path.join(root, 'projects');
  if (!existsSync(projectsDir)) return ok('idea_bank', 0);

  let total = 0;
  let oldest = null;
  for (const proj of await readdir(projectsDir)) {
    const bank = path.join(projectsDir, proj, 'ideation-bank');
    if (!existsSync(bank)) continue;
    for await (const f of walkMd(bank)) {
      total++;
      const parsed = parseFile(f);
      const updated = parsed.data?.updated;
      if (updated && (!oldest || updated < oldest.updated)) {
        oldest = { path: path.relative(root, f), updated };
      }
    }
  }
  return {
    severity: total === 0 ? 'ok' : total > 200 ? 'critical' : total > 100 ? 'warn' : 'ok',
    count: total,
    oldest,
  };
}

// Distillation debt: count pages per level. Useful as a one-glance view of
// "how distilled is the wiki right now". No threshold — it's a snapshot.
async function checkDistillationDebt(root) {
  const wikiDir = path.join(root, 'wiki');
  const buckets = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0, missing: 0 };
  if (!existsSync(wikiDir)) return { severity: 'ok', count: 0, buckets };

  for await (const f of walkMd(wikiDir)) {
    const fm = parseFile(f).data || {};
    const lvl = fm.distillation_level;
    if (lvl === undefined || lvl === null) buckets.missing++;
    else buckets[lvl] = (buckets[lvl] ?? 0) + 1;
  }
  // Critical only if >50% of wiki is level 0/1 (raw or first-pass).
  const total = Object.values(buckets).reduce((a, b) => a + b, 0);
  const undistilled = (buckets[0] ?? 0) + (buckets[1] ?? 0) + buckets.missing;
  const ratio = total > 0 ? undistilled / total : 0;
  const severity = ratio > 0.5 ? 'warn' : 'ok';
  return { severity, count: total, buckets };
}

// AGENTS.md ↔ CLAUDE.md symlink: we want CLAUDE.md to be a symlink to
// AGENTS.md so both Claude Code and any AGENTS.md-aware tool see the same
// content. Drift is a critical finding because the two files diverging
// means one of the agents is reading stale instructions.
async function checkAgentsSymlink(root) {
  const agents = path.join(root, 'AGENTS.md');
  const claude = path.join(root, 'CLAUDE.md');
  if (!existsSync(agents)) return { severity: 'critical', count: 1, detail: 'AGENTS.md missing' };
  if (!existsSync(claude)) return { severity: 'critical', count: 1, detail: 'CLAUDE.md missing — should be a symlink to AGENTS.md' };
  let lstat;
  try {
    lstat = lstatSync(claude);
  } catch {
    return { severity: 'critical', count: 1, detail: 'cannot stat CLAUDE.md' };
  }
  if (!lstat.isSymbolicLink()) {
    return { severity: 'critical', count: 1, detail: 'CLAUDE.md is a regular file, not a symlink to AGENTS.md' };
  }
  const target = readlinkSync(claude);
  if (target !== 'AGENTS.md' && path.basename(target) !== 'AGENTS.md') {
    return { severity: 'critical', count: 1, detail: `CLAUDE.md points to ${target}, expected AGENTS.md` };
  }
  return { severity: 'ok', count: 0 };
}

// log.md rotation: hooks rotate at 3000 lines (≈90 days). We surface when
// the live log is approaching the threshold so the owner isn't surprised.
async function checkLogRotation(root) {
  const logPath = path.join(root, 'log.md');
  if (!existsSync(logPath)) return ok('log_rotation', 0);
  const body = await readFile(logPath, 'utf8');
  const lines = body.split('\n').length;
  return {
    severity: lines > 3000 ? 'warn' : 'ok',
    count: lines,
    detail: `${lines} lines${lines > 3000 ? ' — rotation pending' : ''}`,
  };
}

// Token estimate: rough character-count proxy of how heavy each common
// workflow is. Useful to confirm v2 stays within the <6K target.
async function estimateTokens(root) {
  const targets = {
    bridge_in: ['AGENTS.md', '.cache/status.json'],
    health: ['.cache/status.json', '.cache/backrefs.json'],
    daily: ['inbox/journal/'],
  };
  const out = {};
  for (const [name, files] of Object.entries(targets)) {
    let bytes = 0;
    for (const f of files) {
      const p = path.join(root, f);
      try {
        const s = statSync(p);
        if (s.isFile()) bytes += s.size;
        else if (s.isDirectory()) {
          for await (const sub of walkAll(p, [])) {
            try { bytes += statSync(sub).size; } catch {}
          }
        }
      } catch {}
    }
    // Rough approximation: 1 token ≈ 4 bytes for English/Spanish prose.
    out[name] = { bytes, est_tokens: Math.round(bytes / 4) };
  }
  return { severity: 'ok', count: 0, estimates: out };
}

// =====================================================================
// Output formatting.
// =====================================================================

function printReport(r) {
  console.log(colors.bold(`Kortex health — ${r.date}`));
  console.log('');
  for (const [name, c] of Object.entries(r.checks)) {
    const sev = c.severity || 'ok';
    const icon = sev === 'ok' ? tag.ok() : sev === 'warn' ? tag.warn() : tag.fail();
    const summary = formatCheckSummary(name, c);
    console.log(`${icon}  ${colors.bold(name.padEnd(22))} ${summary}`);
    if (c.items?.length) {
      for (const it of c.items.slice(0, 5)) {
        const detail = typeof it === 'string' ? it : `${it.path}${it.updated ? ` (${it.updated}, lvl ${it.level ?? '-'})` : ''}`;
        console.log(`     ${colors.gray('-')} ${detail}`);
      }
      if (c.items.length > 5) console.log(`     ${colors.gray('… ' + (c.items.length - 5) + ' more')}`);
    }
    if (c.deferred) console.log(`     ${colors.gray('deferred: ' + c.deferred)}`);
    if (c.detail) console.log(`     ${colors.gray(c.detail)}`);
    if (c.estimates) {
      for (const [k, v] of Object.entries(c.estimates)) {
        console.log(`     ${colors.gray(`${k}: ~${v.est_tokens} tok (${v.bytes} bytes)`)}`);
      }
    }
  }
  console.log('');
  const s = r.summary;
  console.log(`Summary: ${colors.green(s.ok + ' ok')}, ${colors.yellow(s.warn + ' warn')}, ${colors.red(s.critical + ' critical')}`);
}

function formatCheckSummary(name, c) {
  if (c.count !== undefined) {
    if (name === 'log_rotation') return c.detail || `${c.count} lines`;
    if (name === 'idea_bank' && c.oldest) return `${c.count} ideas; oldest ${c.oldest.updated}`;
    if (name === 'distillation_debt' && c.buckets) {
      return `total ${c.count} (${Object.entries(c.buckets).map(([k, v]) => `${k}=${v}`).join(' ')})`;
    }
    return `${c.count} item${c.count === 1 ? '' : 's'}`;
  }
  return '';
}

// =====================================================================
// Walkers — minimal, no glob lib needed.
// =====================================================================

async function* walkMd(dir) {
  yield* walkExt(dir, '.md');
}

async function* walkExt(dir, ext) {
  for await (const f of walkAll(dir, ['node_modules', '.git', '.cache', 'processed'])) {
    if (f.endsWith(ext)) yield f;
  }
}

async function* walkAll(dir, exclude) {
  if (!existsSync(dir)) return;
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    if (exclude?.includes(e.name)) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) yield* walkAll(full, exclude);
    else yield full;
  }
}

function ok(name, count = 0) {
  return { severity: 'ok', count };
}

function findRepoRoot(start) {
  let dir = path.resolve(start);
  while (dir !== path.dirname(dir)) {
    if (existsSync(path.join(dir, '.git'))) return dir;
    dir = path.dirname(dir);
  }
  return path.resolve(start);
}

function printHelp() {
  console.log('Usage: pnpm kortex health [--critical] [--tokens] [--json]');
  console.log('');
  console.log('Single-shot wiki health check. Reads .cache/status.json for cheap walks.');
  console.log('');
  console.log('Flags:');
  console.log('  --critical   exit 1 if any critical finding (CI usage)');
  console.log('  --tokens     also estimate token cost of each workflow');
  console.log('  --json       machine-readable output');
}
